apiVersion: v1
kind: Namespace
metadata: { name: user-todo-ns }
---
apiVersion: v1
kind: Namespace
metadata: { name: community-ns }
---
apiVersion: v1
kind: Namespace
metadata: { name: frontend-ns }
---
apiVersion: v1
kind: Namespace
metadata: { name: database-ns }
---