# user-todo deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-todo
  namespace: user-todo-ns
spec:
  replicas: 2
  selector:
    matchLabels: { app: user-todo }
  template:
    metadata:
      labels: { app: user-todo }
    spec:
      containers:
        - name: user-todo
          image: back-queueme-user-todo-service:latest
          imagePullPolicy: Never # local 이미지 사용
          ports: [{ containerPort: 8000 }]
          envFrom:
            - secretRef: { name: app-secrets }
          env:
            - name: TZ
              value: "Asia/Seoul"
---
# user-todo service 
apiVersion: v1
kind: Service
metadata:
  name: user-todo-service
  namespace: user-todo-ns
spec:
  selector: { app: user-todo }
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
# community deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: community
  namespace: community-ns
spec:
  replicas: 2
  selector:
    matchLabels: { app: community }
  template:
    metadata:
      labels: { app: community }
    spec:
      containers:
        - name: community
          image: back-queueme-community-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef: { name: app-secrets }
          env:
            - name: TZ
              value: "Asia/Seoul"
---
# community service 
apiVersion: v1
kind: Service
metadata:
  name: community-service
  namespace: community-ns
spec:
  selector: { app: community }
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000